### ISSUE TITLE
Please don't use the password anti pattern

### ISSUE THREAD

**Issue by bmann** [mishushakov/signin-with-matrix#10]
Putting usernames and passwords for a third party services is an anti pattern and a major security issue. We don't want to train users to put passwords into third party services.

Cactus Comments also does this:

![Screen Shot 2021-11-16 at 9 43 44 AM](https://user-images.githubusercontent.com/280420/142038161-4b3faa89-43bd-4bb5-a162-045d486629ba.png)
 
But includes the "use a matrix client":

![Screen Shot 2021-11-16 at 9 45 50 AM](https://user-images.githubusercontent.com/280420/142038260-c5d08552-2f50-4895-8da5-41258eab05b1.png)

**Comment by mishushakov** [comment]
I appreciate your feedback, but sadly there is no other way for authenticating and getting access tokens in the Matrix protocol

notice, that Cactus does not do auth when you click on "Use a Matrix client"
