### ISSUE TITLE
Add login with bot

### ISSUE THREAD

**Issue by HKalbasi** [mishushakov/signin-with-matrix#11]
Users enter their id, a bot send a token to that id and user will enter that token into the website. In this way there is no need to enter password on the untrusted site.

**Comment by mishushakov** [comment]
I was considering this idea, but it does not work
see: https://github.com/mishushakov/signin-with-matrix/issues/10#issuecomment-970572088

you're can fork this and use it as a starting point for your own project though

**Comment by HKalbasi** [comment]
Can you explain why this need changes to matrix spec, and what change is needed?
