### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by ghost** [mishushakov/signin-with-matrix#17]
1. After im entered login it prints "Network Error"
2. If i fix it can i hardcore only my homeserver to sign in?
![Screenshot_20230908-085827](https://github.com/mishushakov/signin-with-matrix/assets/116358854/78464d3c-792e-4eef-a8b9-3974c3290b99)

**Comment by mishushakov** [comment]
1. Network error maybe because you're not using HTTPS? Are you able to login using Matrix? You need to have a file in `.well-known/matrix/client`
2. It should be possible to make it read-only. Could you start a pull request?

**Comment by ghost** [comment]
I didn't have client file at moment 8 september. Currently have
I'm check now with file and update comment
Upd: no, error still appears
maybe test from pc
Upd 2: seems cors policy blocking
