### ISSUE TITLE
Credential stealing?

### ISSUE THREAD

**Issue by Erudition** [mishushakov/signin-with-matrix#19]
This widget suspiciously requires users to enter their Matrix password directly into the embedded website (something I wouldn't do) rather than taking them to a Matrix server's auth page to simply connect an account.

That's like what a phishing site would do, is there any reason for the user to believe the credentials are guaranteed to be sent only to the homeserver?

**Comment by mishushakov** [comment]
Don't use it, if you don't trust it. The project is 2 years old at this point and maybe some things have changed on the Matrix side...
